[build-system]
requires = [
    "setuptools>=77.0.1",
]
build-backend = "setuptools.build_meta"

[project]
name = "torchgeo"
description = "TorchGeo: datasets, samplers, transforms, and pre-trained models for geospatial data"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    {name = "Adam J. Stewart", email = "ajstewart426@gmail.com"},
]
maintainers = [
    {name = "Adam J. Stewart", email = "ajstewart426@gmail.com"},
    {name = "Caleb Robinson", email = "Caleb.Robinson@microsoft.com"},
    {name = "Isaac Corley", email = "isaac.corley@my.utsa.edu"},
    {name = "Nils Lehmann", email = "n.lehmann@tum.de"},
    {name = "Ashwin Nair", email = "ashnair0007@gmail.com"},
]
keywords = ["pytorch", "deep learning", "machine learning", "remote sensing", "satellite imagery", "earth observation", "geospatial"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: GIS",
]
dependencies = [
    "einops>=0.3",
    "geopandas>=0.13",
    "jsonargparse[signatures]>=4.35",
    "kornia>=0.8.2",
    "lightly>=1.4.5,!=1.4.26",
    "lightning>=2,!=2.3.*,!=2.5.0,!=2.5.5,!=2.5.6",
    "matplotlib>=3.7.3",
    "numpy>=1.26",
    "pandas>=2.1.1",
    "pillow>=10",
    "pyproj>=3.6.1",
    "rasterio>=1.4.3",
    "segmentation-models-pytorch>=0.5",
    "shapely>=2.0.2",
    "timm>=1.0.3",
    "torch>=2.2",
    "torchmetrics>=1.2",
    "torchvision>=0.17",
    "typing-extensions>=4.8",
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "torchgeo.__version__"}

[tool.setuptools.packages.find]
include = ["torchgeo*"]

[tool.ty.src]
include = ["torchgeo", "tests"]
exclude = ["tests/data"]
